### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by ronnievisser** [astroanu/laravel-seo-gen#1]
Currently only this package is keeping me stay with 5.0. I would like to upgrade to 5.1. Can you fix composer.json file?

**Comment by astroanu** [comment]
Can you make make a pull request after changing the composer.json. I'll merge it for you. :) I haven't tested this on a 5.1 project. i'm sure it will still work fine.

**Comment by impartdan** [comment]
+1

**Comment by astroanu** [comment]
try with the latest release (1.1.0) tested on Laravel 5.2
